### ISSUE TITLE
Software Design

### ISSUE THREAD

**Issue by atakanyasar** [bounswe/bounswe2024group1#63]
# 🔍 Issue Tracker

## 📝 Description
This is an issue tracking the Software Design stage of this project. This stage includes all relevant diagrams of the Software Design process such as Sequence, Usecase, Activity, Class diagrams among others. This stage also includes the specification of the API for the backend.

## 📅 Deadline
April 30th, 2024
## 🎯 Issues
| Issue | Description | Deadline | Status |
| ----- | ----------- | ------ | ---- |
|  #65  | API Specification | -  |✅ |
|  #68  |  Create Activity Diagrams | -  | ⏳ |
| #71   |  Create Class Diagram  | -  | ✅ |
| #79 |  Create Use Case Diagram| -| ✅ |
| #104  |  Create Sequence Diagram| -| ✅ |

## 📊 Additional context
- [X] #65  | API Specification
- [ ] #68  |  Create Activity Diagrams 
- [X] #71   |  Create Class Diagram
- [x] #79 |  Create Use Case Diagram
- [X] #104  |  Create Sequence Diagram

**Comment by atakanyasar** [comment]
Class diagram and Sequence diagram is done.

**Comment by atakanyasar** [comment]
Software Design is finished. 

- [The Milestone 2 Report](https://github.com/bounswe/bounswe2024group1/wiki/Milestone%E2%80%902-Report)
